services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8081:8081"
    depends_on:
      db-prod:
        condition: service_healthy
    environment:
      JAVA_ARGS: "-Dspring.profiles.active=prod -Duser.timezone=UTC"
      DATABASE_NAME: "db-prod"
      DB_PASSWORD: ${DB_PASSWORD}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: "api:8081"
    ports:
      - "3000:3000"

  db-prod:
    image: mysql:9.3.0
    environment:
      MYSQL_DATABASE: votifydb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 10
