apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-cluster
  namespace: votify
spec:
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: 10.96.0.60
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80