apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: votify
data:
  API_HOST: votify-api-svc-node
  API_PORT: "8081"
  WEB_HOST: votify-web-svc-node
  WEB_PORT: "3000"
  nginx.conf.template: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;

            location /api/ {
                proxy_pass http://$API_HOST:$API_PORT;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /ws/ {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_pass http://$API_HOST:$API_PORT;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location / {
                proxy_pass http://$WEB_HOST:$WEB_PORT;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }