apiVersion: v1
kind: Service
metadata:
  name: votify-api-svc-node
  namespace: votify
spec:
  selector:
    app: votify-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081  