apiVersion: apps/v1
kind: Deployment
metadata:
  name: votify-api-deploy
  namespace: votify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votify-api
  template:
    metadata:
      labels:
        app: votify-api
    spec:
      containers:
        - name: votify-api
          image: byces/votify-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
      restartPolicy: Always
