# Acesso externo (NodePort)

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-node
  namespace: votify
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006