FROM node:22.15.0-alpine AS builder

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

WORKDIR /build

COPY votify-web /build

RUN yarn install --frozen-lockfile
RUN if [ "$NODE_ENV" = "production" ]; then yarn run build; fi


FROM node:18-alpine

ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

WORKDIR /app

COPY --from=builder /build /app

EXPOSE 3000
CMD if [ "$NODE_ENV" = "development" ]; then \
      yarn run dev; \
    else \
      yarn run start; \
    fi
