FROM maven:3.9.6-eclipse-temurin-17

WORKDIR /build

COPY votify-api votify-api
COPY votify-core votify-core
COPY votify-dto votify-dto
COPY votify-test votify-test
COPY pom.xml pom.xml
COPY checkstyle.xml checkstyle.xml

RUN mvn clean compile

EXPOSE 8081
CMD ["sh", "-c", "\
    mvn checkstyle:check; \
    if [ $? -ne 0 ]; then exit $?; fi; \
    mvn clean verify -Dspring.profiles.active=test; \
    status=$?; \
    cp -r /build/votify-test/target/* /build/votify-test/target-copy; \
    chmod 777 -R /build/votify-test/target-copy; \
    exit $status \
"]
