apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.api.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REFRESH_TOKEN_SECRET: {{ .Values.api.secret.REFRESH_TOKEN_SECRET }}
  MAIL_PASSWORD: {{ .Values.api.secret.MAIL_PASSWORD }}
  DB_PASSWORD: {{ .Values.mysql.secret.MYSQL_ROOT_PASSWORD }}
