apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.mysql.name }}-deploy"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
          imagePullPolicy: {{ .Values.mysql.imagePullPolicy }}
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Values.mysql.name }}-cm"
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mysql.name }}-secret"
                  key: MYSQL_ROOT_PASSWORD
      restartPolicy: Always
