apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.mysql.name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.MYSQL_ROOT_PASSWORD }}
