name: Build Docker Files

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ci-${{ github.sha }}
      API_IMAGE: "byces/votify-api"
      WEB_IMAGE: "byces/votify-web"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker Image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: false
          tags: |
            ${{ env.API_IMAGE }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Web Docker Image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: false
          tags: |
            ${{ env.WEB_IMAGE }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save API image to artifact
        run: docker save ${{ env.API_IMAGE }}:${{ env.VERSION }} -o api-image.tar

      - name: Save Web image to artifact
        run: docker save ${{ env.WEB_IMAGE }}:${{ env.VERSION }} -o web-image.tar

      - name: Upload API image artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-image
          path: api-image.tar

      - name: Upload Web image artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-image
          path: web-image.tar
