name: Commit Badges Action

on:
  workflow_call:
    inputs:
      jacoco-artifact-name:
        description: The name of the jacoco artifact to be downloaded.
        required: true
        type: string

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JaCoCo artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-artifact
          path: .

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          jacoco-csv-file: jacoco.csv
          generate-branches-badge: true
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg

      - name: Commit the badge (if it changed)
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            exit 0
          fi
          git add .
          git stash push -m "Temporary stash for coverage badge update"
          git checkout badges
          git checkout stash@{0} -- .github/badges/*.svg || true
          if [[ `git status --porcelain` ]]; then
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add .
              git commit -m "Autogenerated JaCoCo coverage badge"
              git push --force origin HEAD:badges
          fi