name: Votify Manual Image Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: Put the version that will be added to the image on dockerhub.
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
      API_IMAGE: "byces/votify-api"
      WEB_IMAGE: "byces/votify-web"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-docker-action@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build API Docker Image
        run: |
          docker build -t "$API_IMAGE:$VERSION" -f ./docker/Dockerfile.api .
          docker tag "$API_IMAGE:$VERSION" "$API_IMAGE:latest"

      - name: Build Web Docker Image
        run : |
          docker build -t "$WEB_IMAGE:$VERSION" -f ./docker/Dockerfile.frontend .
          docker tag "$WEB_IMAGE:$VERSION" "$WEB_IMAGE:latest"

      - name: Push API Docker Image
        run: |
          docker push "$API_IMAGE:$VERSION"
          docker push "$API_IMAGE:latest"

      - name: Push Web Docker Image
        run: |
          docker push "$WEB_IMAGE:$VERSION"
          docker push "$WEB_IMAGE:latest"