name: Votify Manual Image Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: Put the version that will be added to the image on dockerhub.
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
      API_IMAGE: "byces/votify-api"
      WEB_IMAGE: "byces/votify-web"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-docker-action@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push API Docker Image (com cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: |
            ${{ env.API_IMAGE }}:${{ env.VERSION }}
            ${{ env.API_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Web Docker Image (com cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: |
            ${{ env.WEB_IMAGE }}:${{ env.VERSION }}
            ${{ env.WEB_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max