name: Docker Vulnerability Scan

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: 'Name of the Docker image to be scanned'

jobs:
  scan:
    name: Scan Docker Image ${{ inputs.image_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan image with Trivy
        run: |
          echo "🔍 Scanning image: ${{ inputs.image_name }}"
          trivy image \
            --exit-code 1 \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            ${{ inputs.image_name }}
