name: Docker Vulnerability Scan

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Determine artifact name
        id: set-artifact
        run: |
          if [[ "${{ inputs.image_name }}" == "byces/votify-api" ]]; then
            echo "artifact_name=api-image" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.image_name }}" == "byces/votify-web" ]]; then
            echo "artifact_name=web-image" >> $GITHUB_OUTPUT
          else
            echo "Unknown image name"
            exit 1
          fi

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.set-artifact.outputs.artifact_name }}
          path: .

      - name: Load Docker image
        run: |
          if [[ "${{ steps.set-artifact.outputs.artifact_name }}" == "api-image" ]]; then
            docker load -i api-image.tar
          else
            docker load -i web-image.tar
          fi

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker image
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ inputs.image_name }}:${{ inputs.image_version }}
