name: Docker Vulnerability Scan

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Determine artifact name
        id: set-artifact
        run: |
          case "${{ inputs.image_name }}" in
            "byces/votify-api") echo "artifact_name=api-image" >> $GITHUB_OUTPUT ;;
            "byces/votify-web") echo "artifact_name=web-image" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown image name" >&2; exit 1 ;;
          esac

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.set-artifact.outputs.artifact_name }}
          path: .

      - name: Load Docker image
        run: |
          docker load -i ${{ steps.set-artifact.outputs.artifact_name }}.tar

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker image
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH "${{ inputs.image_name }}:${{ inputs.image_version }}"
