name: Votify Java CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - '**/*.properties'
      - '**/*.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and install all modules
        run: mvn clean compile

      - name: Run tests with Maven and Jacoco
        run: mvn clean verify

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          jacoco-csv-file: votify-test/target/site/jacoco-aggregate/jacoco.csv
          generate-branches-badge: true
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git stash push -m "Temporary stash for coverage badge update" --include-untracked
            git checkout badges
            git stash pop
            if [[ `git status --porcelain` ]]; then
                git config --global user.name 'Leonardo Teixeira'
                git config --global user.email 'leonardo-tx@users.noreply.github.com'
                git add -A
                git commit -m "Autogenerated JaCoCo coverage badge"
                git push origin HEAD:badges
            fi
          fi
