name: Votify Java CI

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - '**/*.properties'
      - '**/*.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker Compose
        run: |
          sudo apt update
          sudo apt install docker-compose -y

      - name: Build docker compose test
        run: docker-compose -f ./docker/docker-compose.test.yml build

      - name: Run tests from docker compose test
        run: docker-compose -f ./docker/docker-compose.test.yml up --abort-on-container-exit --exit-code-from test

      - name: Generate Jacoco Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-artifact
          path: docker/target/site/jacoco-aggregate/jacoco.*

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          jacoco-csv-file: docker/target/site/jacoco-aggregate/jacoco.csv
          generate-branches-badge: true
          coverage-badge-filename: jacoco.svg
          branches-badge-filename: branches.svg

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git add .
            git stash push
            git checkout badges
            git checkout stash@{0} -- .github/badges/*.svg || true
            if [[ `git status --porcelain` ]]; then
                git config --global user.name 'Leonardo Teixeira'
                git config --global user.email 'leonardo-tx@users.noreply.github.com'
                git add .
                git commit -m "Autogenerated JaCoCo coverage badge"
                git push --force origin HEAD:badges
            fi
          fi
  sonar:
    needs: test
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
    with:
      jacoco-artifact-name: jacoco-artifact