name: Votify Pull request Java CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - '**/*.properties'
      - '**/*.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./.github/actions/test
        with:
          fetch-depth: '1'
          maven-goal: 'test'
          upload-artifacts: 'false'