name: Votify Pull Request Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - '**/*.properties'
      - '**/*.yml'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload-artifacts: true

  docker-scan-api:
    needs: test
    uses: ./.github/workflows/docker-vuln-scan.yml
    with:
      image_name: votify-api:latest

  docker-scan-frontend:
    needs: test
    uses: ./.github/workflows/docker-vuln-scan.yml
    with:
      image_name: votify-frontend:latest

  docker-scan-test:
    needs: test
    uses: ./.github/workflows/docker-vuln-scan.yml
    with:
      image_name: votify-test:latest

  coverage:
    needs: test
    uses: ./.github/workflows/coverage.yml
    with:
      jacoco-artifact-name: jacoco-artifact

  sonar:
    needs: coverage
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
    with:
      jacoco-artifact-name: jacoco-artifact
