name: Votify Pull request Java CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/pom.xml'
      - '**/*.properties'
      - '**/*.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install web dependencies
        run: npm install
        working-directory: ./votify-web

      - name: Build web application
        run: npm run build
        working-directory: ./votify-web

      - name: Run web application in background
        run: npm run start &
        working-directory: ./votify-web

      - name: Build and install all modules
        run: mvn clean compile

      - name: Run tests with Maven
        run: mvn clean test